### ISSUE TITLE
少了个文件

### ISSUE THREAD

**Issue by Spj-Zhao** [aiotrobot/handeye-calib#1]
base_hand_on_eye_calib.py文件没有
运行的时候报错了:
ERROR: cannot launch node of type [handeye-calib/base_hand_on_eye_calib.py]: Cannot locate node of type [base_hand_on_eye_calib.py] in package [handeye-calib]. Make sure file exists in package path and permission is set to executable (chmod +x)

**Comment by fishros** [comment]
有添加对应文件的可执行权限吗？

**Comment by Spj-Zhao** [comment]
嗯嗯，是这样问题，前几天已经解决了

**Comment by fishros** [comment]
好的，那我先关闭这个issue，有问题可以再提出。
